config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :postts
  resources :posts do
  	resources :comments
  end
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/postt.rb
class Postt < ApplicationRecord
end

app/controllers/postts_controller.rb
class PosttsController < ApplicationController
  before_action :set_postt, only: %i[ show edit update destroy ]

  # GET /postts or /postts.json
  def index
    @postt = Postt.new
    @postts = Postt.all
  end

  # GET /postts/1 or /postts/1.json
  def show
  end

  # GET /postts/new
  def new
    @postt = Postt.new
  end

  # GET /postts/1/edit
  def edit
  end

  # POST /postts or /postts.json
  def create
    @postt = Postt.new
    @postts = Postt.all
    @postt_data = Postt.new(postt_params)
    if @postt_data.save
      respond_to do |format|
        format.html { redirect_to postts_url } 
        format.js  # <-- will render `app/views/posts/update.js.erb`
      end
    else
      render "new"
    end
    # respond_to do |format|
    #   if @postt.save
    #     format.html { redirect_to @postt, notice: "Postt was successfully created." }
    #     format.json { render :show, status: :created, location: @postt }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @postt.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /postts/1 or /postts/1.json
  def update
    respond_to do |format|
      if @postt.update(postt_params)
        format.html { redirect_to @postt, notice: "Postt was successfully updated." }
        format.json { render :show, status: :ok, location: @postt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @postt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postts/1 or /postts/1.json
  def destroy
    @postt.destroy
    respond_to do |format|
      format.html { redirect_to postts_url, notice: "Postt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postt
      @postt = Postt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def postt_params
      params.require(:postt).permit(:name, :description)
    end
end

app/helpers/postts_helper.rb
module PosttsHelper
end

app/views/postts/_datta.html.erb
<h1>Postts</h1>
<%= render 'form', postt: @postt %>

<table id="dttb" class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @postts.each do |postt| %>
      <tr>
        <td><%= postt.name %></td>
        <td><%= postt.description %></td>
        <td><%= image_tag post.image_url rescue nil %></td>
        <td><%= link_to 'Show', postt %>
        <%= link_to 'Edit', edit_postt_path(postt) %>
        <%= link_to 'Destroy', postt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
      $("#dttb").dataTable();
    }); 
  </script>

<br>

<%= link_to 'New Postt', new_postt_path %>

app/views/postts/_form.html.erb
<div class="abc">
  <%= form_with(model: postt, local: false, :remote => true) do |form| %>
  <% if postt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(postt.errors.count, "error") %> prohibited this postt from being saved:</h2>

      <ul>
        <% postt.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/postts/create.js.erb
$('#postt_datta').html("<%= escape_javascript render "/postts/datta", postt: @postt %>");
alert("done");

app/views/postts/edit.html.erb
<h1>Editing Postt</h1>

<%= render 'form', postt: @postt %>

<%= link_to 'Show', @postt %> |
<%= link_to 'Back', postts_path %>

app/views/postts/index.html.erb
<p id="notice"><%= notice %></p>

<div id="postt_datta">
  <%= render :partial => "datta", locals: {postts: @postts} %>
</div>  

app/views/postts/new.html.erb
<h1>New Postt</h1>

<%= render 'form', postt: @postt %>

<%= link_to 'Back', postts_path %>

app/views/postts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @postt.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @postt.description %>
</p>

<%= link_to 'Edit', edit_postt_path(@postt) %> |
<%= link_to 'Back', postts_path %>